[package]
name = "agent"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libcrux-agent.workspace = true
libcrux-hmac-drbg = {features = ["rand"], workspace = true}

ipc-channel = "0.21.0"
libc = "0.2.183"
rand = { version = "0.10" }
zerocopy = {version="0.8.47", features = ["derive", "std"]}
