[package]
name = "agent-setup"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]

base64ct = "1.8.3"
hex = "0.4"
ipc-channel = "0.21.0"
rand = { version = "0.10" }
zerocopy = {version="0.8.47", features = ["derive", "std"]}

libcrux-agent.workspace = true
