[package]
name = "libcrux-primitive-api"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libcrux-agent.workspace = true
libcrux-curve25519.workspace = true
libcrux-ecdsa.workspace = true
libcrux-ed25519.workspace = true
libcrux-hkdf.workspace = true
libcrux-ml-kem.workspace=true
libcrux-ml-kem.default-features=true
libcrux-sha2.workspace=true

der = { git = "https://github.com/kraemv/formats", rev = "c2da52f7", features = ["alloc", "oid"]}
pkcs8 = { git = "https://github.com/kraemv/formats", rev = "c2da52f7", features = ["pem"]}
pki-types = { package = "rustls-pki-types", version = "1" }
x509-cert = { git = "https://github.com/kraemv/formats", rev = "c2da52f7", default-features = false }