[package]
name = "libcrux-primitive-api"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libcrux-agent.workspace = true
libcrux-ecdsa.workspace = true
libcrux-ed25519.workspace = true