[package]
name = "libcrux-primitive-api"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
libcrux-agent.workspace = true
libcrux-curve25519.workspace = true
libcrux-ecdsa.workspace = true
libcrux-ed25519 = {workspace = true, features = ["rand"]}
libcrux-ml-kem.workspace=true
libcrux-ml-kem.default-features=true

rand = { version = "0.9" }
rand_chacha = "0.9.0"